M48
; DRILL file {KiCad 7.0.5-0} date 2023 July 10, Monday 11:09:01
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-10T11:09:01-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.6969Y-2.7532
X3.6969Y-5.4697
X5.4528Y-2.7532
X5.4528Y-5.4697
T0
M30
